services:
  mysql:
    image: mysql:8.0
    container_name: db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: usr_db
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
      build:
        context: ./usr-api
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      container_name: usrapi_container
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/usr_db
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: admin

  react-app:
      build:
        context: ./usr-ui
        dockerfile: Dockerfile
      container_name: usrui_container
      ports:
        - "3000:80"

volumes:
  mysql_data: