server:
  port: 8080
spring:
  application:
    name: "user-api"
  datasource:
    url: "jdbc:mysql://localhost:3306/usr_db"
    username: "admin"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true